---
language: python      # to use coala (https://coala.io/)
python: "3.6"

addons:
  apt:
    sources:
      - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
      - shellcheck

cache:
  pip: true
  directories:
    - tests/.bats
    - tests/.helper-libs

install:
  - pip install -r test-requirements.txt

script:
  - coala --non-interactive
  - tests/run.sh
